# NFL Team dictionary with team abbreviation as keys and team name as the values
NFL_TEAMS = {
    'CRD': 'Cardinals',
    'ATL': 'Falcons',
    'RAV': 'Ravens',
    'BUF': 'Bills',
    'CAR': 'Panthers',
    'CHI': 'Bears',
    'CIN': 'Bengals',
    'CLE': 'Browns',
    'DAL': 'Cowboys',
    'DEN': 'Broncos',
    'DET': 'Lions',
    'GNB': 'Packers',
    'HTX': 'Texans',
    'CLT': 'Colts',
    'JAX': 'Jaguars',
    'KAN': 'Chiefs',
    'RAI': 'Raiders',
    'SDG': 'Chargers',
    'RAM': 'Rams',
    'MIA': 'Dolphins',
    'MIN': 'Vikings',
    'NWE': 'Patriots',
    'NOR': 'Saints',
    'NYG': 'Giants',
    'NYJ': 'Jets',
    'PHI': 'Eagles',
    'PIT': 'Steelers',
    'SFO': '49ers',
    'SEA': 'Seahawks',
    'TAM': 'Buccaneers',
    'OTI': 'Titans',
    'WAS': 'Commanders'
}